### PR TITLE
Feature/custom serializable

### LINKED ISSUE #10: Serializing abstract class
Hi Nicolas,

I need to serialize a quite specific file: a `Float32Array`.
The file is an abstract and I'm lost on how to make it serializable...

https://github.com/FishingCactus/lime/blob/develop/lime/utils/Float32Array.hx

Can you give some feedback?

Thanks

### PR DESCRIPTION
**Pull request by NuclearCookie**
Addes support for custom serializable classes.
Example included in readme page. 
Tested and works like a charm!

Fixes #10

### CODE REVIEW

**Comment by ncannasse** [comment]
Hi,

Thank you for the PR
However I'm not much fan of the distinction between three interfaces Serializable/BaseSerializable/CustomSerializable.

Maybe another approach would be like this:

If the class has functions customSerialize  and customUnserialize, call them at the end of serialize/unseriliaze (unless their are override, in which case our superclass will do for us).

This allow to mix some properties having `@:s` support and some others being custom-serialized, and still allow to subclass the class without disrupting the whole serialization.

**Comment by NuclearCookie** [comment]
Done. Much simpler indeed!

**Comment by ncannasse** [comment]
Nice ! out of curiosity, was @:keep in the documentation necessary ? since it's referenced from serialize/unserialize, it should not be required.

**Comment by NuclearCookie** [comment]
That's true. It might not have been necessary!

**Pull request merged**
